"""Resolve every DOI, build the reference list from what resolves, and check the text against it.

A reference written from memory is a reference that points somewhere else. Three of them in a
previous manuscript from this group resolved to different papers than the ones intended, and
nothing in the text showed it. So nothing here is typed: paper/references.json holds keys and
DOIs, this resolves each one against Crossref (or DataCite, for arXiv and dataset DOIs),
formats the entry from the resolved record, and writes the manuscript's reference section.

It also works in the other direction. Every author-year citation in the prose must match a
resolved record, and every resolved record must be cited at least once, so a citation cannot
drift from its reference and a reference cannot sit unused.

    python paper/check_references.py            # check, and rewrite the reference section
    python paper/check_references.py --check     # check only, change nothing
"""

from __future__ import annotations

import json
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parent
REFERENCES = HERE / "references.json"
RESOLVED = HERE / "frozen" / "references_resolved.json"
MANUSCRIPT = HERE / "manuscript.md"
MAILTO = "yamamoto@lisit.jp"

BEGIN = "<!-- references: generated by paper/check_references.py; do not edit by hand -->"
END = "<!-- end references -->"


def crossref(doi: str):
    url = f"https://api.crossref.org/works/{urllib.parse.quote(doi)}?mailto={MAILTO}"
    request = urllib.request.Request(url, headers={"User-Agent": f"IORN-011 ({MAILTO})"})
    with urllib.request.urlopen(request, timeout=60) as response:
        item = json.loads(response.read().decode("utf-8"))["message"]
    authors = []
    for author in item.get("author") or []:
        family = author.get("family")
        if family:
            initials = "".join(part[0] for part in (author.get("given") or "").replace(".", " ").split() if part)
            authors.append({"family": family, "initials": initials})
        elif author.get("name"):
            authors.append({"family": author["name"], "initials": ""})
    return {
        "source": "crossref",
        "authors": authors,
        "year": (item.get("issued", {}).get("date-parts") or [[None]])[0][0],
        "title": (item.get("title") or [""])[0],
        "container": (item.get("container-title") or [""])[0],
        "volume": item.get("volume"),
        "pages": item.get("page"),
        "type": item.get("type"),
    }


def datacite(doi: str):
    url = f"https://api.datacite.org/dois/{urllib.parse.quote(doi, safe='')}"
    with urllib.request.urlopen(url, timeout=60) as response:
        item = json.loads(response.read().decode("utf-8"))["data"]["attributes"]
    authors = []
    for creator in item.get("creators") or []:
        family = creator.get("familyName") or creator.get("name") or ""
        given = creator.get("givenName") or ""
        initials = "".join(part[0] for part in given.replace(".", " ").split() if part)
        if family:
            authors.append({"family": family, "initials": initials})
    return {
        "source": "datacite",
        "authors": authors,
        "year": item.get("publicationYear"),
        "title": (item.get("titles") or [{}])[0].get("title", ""),
        "container": (item.get("publisher") or {}).get("name")
        if isinstance(item.get("publisher"), dict) else item.get("publisher"),
        "volume": None,
        "pages": None,
        "type": (item.get("types") or {}).get("resourceTypeGeneral"),
    }


def resolve(entry: dict) -> dict:
    doi = entry["doi"]
    errors = []
    for resolver in ((datacite, crossref) if entry.get("dataset") or "arxiv" in doi.lower()
                     else (crossref, datacite)):
        try:
            record = resolver(doi)
            if record["title"]:
                record["doi"] = doi
                record["key"] = entry["key"]
                record["dataset"] = bool(entry.get("dataset"))
                return record
        except Exception as error:                        # noqa: BLE001 - collected, reported
            errors.append(f"{resolver.__name__}: {error}")
    raise SystemExit(f"{entry['key']} ({doi}) did not resolve — {'; '.join(errors)}")


def author_string(record: dict) -> str:
    """IOP style: up to three named, then 'et al'."""
    authors = record["authors"]
    if not authors:
        return "Anon"
    names = [f"{_family(a['family'])}"
             f"{(' ' + ' '.join(a['initials'])) if a['initials'] else ''}"
             for a in authors]
    if len(names) == 1:
        return names[0]
    if len(names) <= 3:
        return ", ".join(names[:-1]) + " and " + names[-1]
    return names[0] + " et al"


def _family(name: str) -> str:
    """Publishers spell the same surname two ways; a manuscript may not.

    Crossref carries Kachelriess for one paper and Kachelrieß for another, and a corporate
    author arrives with a leading article. Normalising here keeps the prose consistent
    without letting the check pass on a name that is actually different.
    """
    name = re.sub(r"^The ", "", name)
    return name.replace("ss", "ß") if "Kachelrie" in name else name


def citation_string(record: dict) -> str:
    """The author-year form the prose must use."""
    authors = record["authors"]
    if not authors:
        return f"Anon {record['year']}"
    if len(authors) == 1:
        return f"{_family(authors[0]['family'])} {record['year']}"
    if len(authors) == 2:
        return (f"{_family(authors[0]['family'])} and "
                f"{_family(authors[1]['family'])} {record['year']}")
    return f"{_family(authors[0]['family'])} et al {record['year']}"


def format_entry(record: dict) -> str:
    # Crossref titles carry publisher markup: one of these reaches the page as
    # "Clinical <sup>18</sup>F-FDG PET/CT" unless it is stripped.
    title = re.sub(r"<[^>]+>", "", record["title"])
    parts = [author_string(record), str(record["year"]), title]
    line = f"{parts[0]} {parts[1]} {parts[2]}"
    if record["dataset"]:
        line += f" (dataset) {record['container'] or 'The Cancer Imaging Archive'}"
    else:
        if record["container"]:
            line += f" *{record['container']}*"
        if record["volume"]:
            line += f" **{record['volume']}**"
        if record["pages"]:
            line += f" {record['pages'].replace('-', '–')}"
    return line + f" (DOI: {record['doi']})"


def main() -> int:
    check_only = "--check" in sys.argv
    entries = json.loads(REFERENCES.read_text(encoding="utf-8"))["references"]
    keys = [e["key"] for e in entries]
    if len(keys) != len(set(keys)):
        raise SystemExit("duplicate key in references.json")

    records = []
    for entry in entries:
        record = resolve(entry)
        records.append(record)
        print(f"  {record['key']:22s} {citation_string(record):34s} {record['title'][:58]}")
        time.sleep(0.4)

    RESOLVED.parent.mkdir(parents=True, exist_ok=True)
    RESOLVED.write_text(json.dumps(records, indent=1, ensure_ascii=False), encoding="utf-8")

    text = MANUSCRIPT.read_text(encoding="utf-8")
    body = text.split("## References")[0]

    # Every citation in the prose must be one of these, and every reference must be used.
    problems = []
    cited = set()
    for record in records:
        if record["dataset"]:
            continue
        if citation_string(record) in body:
            cited.add(record["key"])
        else:
            problems.append(f"never cited in the text: {record['key']} "
                            f"-> expected '({citation_string(record)})'")
    # A parenthesis may hold several citations separated by commas, so the contents are
    # split before matching. Scanning only whole parentheses let a wrong year inside a
    # multiple citation pass unnoticed, which an injection test caught.
    known = {citation_string(r) for r in records}
    for parenthetical in re.findall(r"\(([^()]{4,200})\)", body):
        for fragment in parenthetical.split(","):
            fragment = fragment.strip()
            if not re.fullmatch(r"[A-ZÀ-Ý][^,]*?\s\d{4}[a-z]?", fragment):
                continue
            if fragment not in known:
                problems.append(
                    f"citation in the text with no resolved reference: ({fragment})")

    listing = "\n\n".join(f"{index + 1}. {format_entry(r)}" for index, r in enumerate(
        sorted(records, key=lambda r: (r["authors"][0]["family"] if r["authors"] else "",
                                       str(r["year"])))))
    section = f"## References\n\n{BEGIN}\n\n{listing}\n\n{END}\n"

    if problems:
        for problem in problems:
            print(f"  FAIL {problem}")
        print(f"\n{len(problems)} problem(s); the reference section was not written")
        return 1

    if not check_only:
        MANUSCRIPT.write_text(body + section, encoding="utf-8")
        print(f"\nreference section written: {len(records)} entries")
    else:
        print(f"\n{len(records)} references resolve and every one is cited")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
